using System.Globalization;
using System.Text;

// Reads the Unicode Character Database files checked into data/ucd and emits
// src/RtlFix.Core/Generated/UnicodeTables.g.cs.

var root = FindRepoRoot();
var ucd = Path.Combine(root, "data", "ucd");
var outDir = Path.Combine(root, "src", "RtlFix.Core", "Generated");
Directory.CreateDirectory(outDir);

var bidi = ParseBidiRanges(Path.Combine(ucd, "DerivedBidiClass.txt"), BidiClasses());
var joining = ParseBidiRanges(Path.Combine(ucd, "DerivedJoiningType.txt"), JoiningClasses());
var mirrors = ParseMirrorPairs(Path.Combine(ucd, "BidiMirroring.txt"));
var brackets = ParseBrackets(Path.Combine(ucd, "BidiBrackets.txt"));
var shaping = ParseShapingForms(Path.Combine(ucd, "UnicodeData.txt"), joining);

var sb = new StringBuilder();
sb.AppendLine("// <auto-generated/>");
sb.AppendLine("// Generated by tools/RtlFix.GenTables from the Unicode Character Database (data/ucd).");
sb.AppendLine("// Run `dotnet run --project tools/RtlFix.GenTables` after updating the data.");
sb.AppendLine();
sb.AppendLine("namespace RtlFix.Core.Unicode;");
sb.AppendLine();
sb.AppendLine("/// <summary>Bidi_Class values from UAX #44 / UAX #9.</summary>");
sb.AppendLine("public enum BidiClass : byte");
sb.AppendLine("{");
foreach (var name in BidiClasses().Keys.OrderBy(k => Array.IndexOf(BidiClassOrder(), k)))
    sb.AppendLine($"    {name},");
sb.AppendLine("}");
sb.AppendLine();
sb.AppendLine("/// <summary>Joining_Type values, used by the Persian/Arabic shaping step.</summary>");
sb.AppendLine("public enum JoiningType : byte");
sb.AppendLine("{");
foreach (var name in JoiningClasses().Keys.OrderBy(k => Array.IndexOf(JoiningOrder(), k)))
    sb.AppendLine($"    {name},");
sb.AppendLine("}");
sb.AppendLine();
sb.AppendLine("/// <summary>Role of a character inside a bracket pair (UAX #9 rules W2 and L4).</summary>");
sb.AppendLine("public enum BracketType : byte");
sb.AppendLine("{");
sb.AppendLine("    None = 0,");
sb.AppendLine("    Open = 1,");
sb.AppendLine("    Close = 2,");
sb.AppendLine("}");
sb.AppendLine();
sb.AppendLine("/// <summary>Contextual glyph form chosen by the shaping step.</summary>");
sb.AppendLine("public enum JoiningForm : byte");
sb.AppendLine("{");
sb.AppendLine("    Isolated = 0,");
sb.AppendLine("    Final = 1,");
sb.AppendLine("    Initial = 2,");
sb.AppendLine("    Medial = 3,");
sb.AppendLine("}");
sb.AppendLine();
sb.AppendLine("/// <summary>Character property tables. See UnicodeTables.cs for the lookup helper.</summary>");
sb.AppendLine("public static partial class UnicodeTables");
sb.AppendLine("{");
EmitRangeTable(sb, "BidiClass", bidi);
EmitRangeTable(sb, "JoiningType", joining);
EmitIntLookup(sb, "Mirror", mirrors);
EmitBracketTables(sb, brackets);
EmitIntLookup(sb, "Presentation", shaping);
sb.AppendLine("}");

var target = Path.Combine(outDir, "UnicodeTables.g.cs");
File.WriteAllText(target, sb.ToString());
Console.WriteLine($"{target}");
Console.WriteLine($"  bidi ranges      : {bidi.Count}");
Console.WriteLine($"  joining ranges   : {joining.Count}");
Console.WriteLine($"  mirroring pairs  : {mirrors.Count}");
Console.WriteLine($"  bracket pairs    : {brackets.Count}");
Console.WriteLine($"  shaping forms    : {shaping.Count}");

// Unicode's own spelling order, so the generated enum reads like the spec.
static string[] BidiClassOrder() =>
[
    "L", "R", "AL", "EN", "AN", "ES", "ET", "CS", "NSM", "BN", "B", "S", "WS", "ON",
    "LRE", "LRO", "RLE", "RLO", "PDF", "LRI", "RLI", "FSI", "PDI",
];

static Dictionary<string, byte> BidiClasses() => BuildMap(BidiClassOrder());

// Joining_Type defaults to Non_Joining, so it must stay at index 0: gaps in the data file
// resolve to "does not join".
static string[] JoiningOrder() => ["U", "T", "R", "L", "D", "C", "S"];

static Dictionary<string, byte> JoiningClasses() => BuildMap(JoiningOrder());


static Dictionary<string, byte> BuildMap(string[] keys)
{
    var map = new Dictionary<string, byte>();
    for (var i = 0; i < keys.Length; i++) map[keys[i]] = (byte)i;
    return map;
}

static List<Range> ParseBidiRanges(string path, Dictionary<string, byte> classes)
{
    var ranges = new List<Range>();
    foreach (var record in ReadRecords(path))
    {
        var fields = record.Split(';');
        var (start, end) = ParseRange(fields[0]);
        // The class name is the first token of the second field; comments are stripped upstream.
        var name = fields[1].Trim().Split(' ')[0];
        if (!classes.TryGetValue(name, out var value))
            throw new InvalidOperationException($"Unknown class '{name}' in: {record}");
        ranges.Add(new Range(start, end, value));
    }
    return Merge(ranges);
}

static List<(int key, int value)> ParseMirrorPairs(string path)
{
    var map = new Dictionary<int, int>();
    foreach (var record in ReadRecords(path))
    {
        var fields = record.Split(';');
        map[Hex(fields[0])] = Hex(fields[1]);
    }
    return map.OrderBy(x => x.Key).Select(x => (x.Key, x.Value)).ToList();
}

static List<(int key, int value)> ParseBrackets(string path)
{
    // Encoded as key = codePoint, value = pairedBracket, and a side table for open/close.
    var entries = new List<(int key, int value)>();
    foreach (var record in ReadRecords(path))
    {
        var fields = record.Split(';');
        var cp = Hex(fields[0]);
        var paired = Hex(fields[1]);
        var isClose = fields[2].Trim() == "c";
        // Bracket type is recoverable from the pair: the smaller mapping direction stores
        // open brackets as (cp -> paired) and closes as a negative marker in the value.
        entries.Add((cp, isClose ? -paired - 1 : paired));
    }
    return entries.OrderBy(x => x.key).ToList();
}

/// <summary>
/// Builds the (base letter, joining form) -> presentation form map from the canonical
/// decomposition mappings in UnicodeData.txt. Entries tagged &lt;isolated&gt;, &lt;final&gt;,
/// &lt;initial&gt; or &lt;medial&gt; decompose to their base letter, which covers both Arabic
/// Presentation Forms-A (where the Persian letters such as PEH live) and Forms-B.
/// </summary>
static List<(int key, int value)> ParseShapingForms(string unicodeDataPath, List<Range> joining)
{
    var joiningOf = new Dictionary<int, byte>();
    foreach (var r in joining)
        for (var cp = r.Start; cp <= r.End; cp++)
            joiningOf[cp] = r.Value;

    var entries = new Dictionary<int, int>();

    foreach (var line in File.ReadLines(unicodeDataPath))
    {
        var fields = line.Split(';');
        if (fields.Length < 6) continue;
        var decomposition = fields[5].Trim();

        JoiningForm? form = null;
        var tagLength = 0;
        foreach (var (tag, value) in FormTags())
        {
            if (!decomposition.StartsWith(tag, StringComparison.Ordinal)) continue;
            form = value;
            tagLength = tag.Length;
            break;
        }
        if (form is null) continue;

        // Exactly one base code point means a contextual form of a single letter; wider
        // decompositions are ligatures or spacing marks and must not be substituted.
        var baseTokens = decomposition[tagLength..]
            .Split(' ', StringSplitOptions.RemoveEmptyEntries);
        if (baseTokens.Length != 1) continue;

        var baseCp = Hex(baseTokens[0]);
        if (!joiningOf.TryGetValue(baseCp, out var jt)) continue;
        // Non_Joining and Transparent letters never take a contextual form.
        if (jt == JoiningOf("U") || jt == JoiningOf("T")) continue;
        entries[baseCp * 4 + (int)form] = Hex(fields[0]);
    }

    return entries.OrderBy(x => x.Key).Select(x => (x.Key, x.Value)).ToList();
}

static Dictionary<string, JoiningForm> FormTags() => new()
{
    ["<isolated>"] = JoiningForm.Isolated,
    ["<final>"] = JoiningForm.Final,
    ["<initial>"] = JoiningForm.Initial,
    ["<medial>"] = JoiningForm.Medial,
};

static byte JoiningOf(string name) => JoiningClasses()[name];

static IEnumerable<string> ReadRecords(string path)
{
    foreach (var line in File.ReadLines(path))
    {
        var trimmed = line.Trim();
        if (trimmed.Length == 0 || trimmed.StartsWith('#')) continue;
        yield return trimmed.Split('#')[0].Trim();
    }
}

static (int start, int end) ParseRange(string field)
{
    var parts = field.Trim().Split("..");
    var start = Hex(parts[0]);
    return (start, parts.Length == 1 ? start : Hex(parts[1]));
}

static int Hex(string s) => int.Parse(s.Trim(), NumberStyles.HexNumber);

static List<Range> Merge(List<Range> input)
{
    var result = new List<Range>();
    foreach (var r in input.OrderBy(x => x.Start).ThenBy(x => x.End))
    {
        if (result.Count > 0 && result[^1].Value == r.Value && result[^1].End + 1 >= r.Start)
        {
            var last = result[^1];
            result[^1] = last with { End = Math.Max(last.End, r.End) };
            continue;
        }
        if (result.Count > 0 && result[^1].End >= r.End) continue;
        result.Add(r);
    }
    return result;
}

static void EmitRangeTable(StringBuilder sb, string name, List<Range> ranges)
{
    sb.AppendLine($"    static readonly int[] {name}Starts =");
    sb.AppendLine($"    {{");
    sb.AppendLine(Numbers(ranges.Select(x => x.Start)));
    sb.AppendLine($"    }};");
    sb.AppendLine();
    sb.AppendLine($"    static readonly int[] {name}Ends =");
    sb.AppendLine($"    {{");
    sb.AppendLine(Numbers(ranges.Select(x => x.End)));
    sb.AppendLine($"    }};");
    sb.AppendLine();
    sb.AppendLine($"    static readonly byte[] {name}Values =");
    sb.AppendLine($"    {{");
    sb.AppendLine(Numbers(ranges.Select(x => (int)x.Value)));
    sb.AppendLine($"    }};");
    sb.AppendLine();
    sb.AppendLine($"    public static {name} Get{name}(int codePoint) => ({name})Lookup({name}Starts, {name}Ends, {name}Values, codePoint);");
    sb.AppendLine();
}

static void EmitIntLookup(StringBuilder sb, string name, List<(int key, int value)> entries)
{
    sb.AppendLine($"    static readonly int[] {name}Keys =");
    sb.AppendLine($"    {{");
    sb.AppendLine(Numbers(entries.Select(x => x.key)));
    sb.AppendLine($"    }};");
    sb.AppendLine();
    sb.AppendLine($"    static readonly int[] {name}Values =");
    sb.AppendLine($"    {{");
    sb.AppendLine(Numbers(entries.Select(x => x.value)));
    sb.AppendLine($"    }};");
    sb.AppendLine();
    sb.AppendLine($"    public static int Get{name}(int key)");
    sb.AppendLine("    {");
    sb.AppendLine($"        var i = Array.BinarySearch({name}Keys, key);");
    sb.AppendLine($"        return i < 0 ? -1 : {name}Values[i];");
    sb.AppendLine("    }");
    sb.AppendLine();
}

static void EmitBracketTables(StringBuilder sb, List<(int key, int value)> entries)
{
    sb.AppendLine($"    static readonly int[] BracketKeys =");
    sb.AppendLine($"    {{");
    sb.AppendLine(Numbers(entries.Select(x => x.key)));
    sb.AppendLine($"    }};");
    sb.AppendLine();
    sb.AppendLine($"    static readonly int[] BracketValues =");
    sb.AppendLine($"    {{");
    sb.AppendLine(Numbers(entries.Select(x => x.value)));
    sb.AppendLine($"    }};");
    sb.AppendLine();
    sb.AppendLine("    /// <summary>Matching bracket for a code point, or -1 when it is not a bracket.</summary>");
    sb.AppendLine("    public static int GetPairedBracket(int codePoint)");
    sb.AppendLine("    {");
    sb.AppendLine("        var i = Array.BinarySearch(BracketKeys, codePoint);");
    sb.AppendLine("        if (i < 0) return -1;");
    sb.AppendLine("        var v = BracketValues[i];");
    sb.AppendLine("        return v < 0 ? -v - 1 : v;");
    sb.AppendLine("    }");
    sb.AppendLine();
    sb.AppendLine("    public static BracketType GetBracketType(int codePoint)");
    sb.AppendLine("    {");
    sb.AppendLine("        var i = Array.BinarySearch(BracketKeys, codePoint);");
    sb.AppendLine("        if (i < 0) return BracketType.None;");
    sb.AppendLine("        return BracketValues[i] < 0 ? BracketType.Close : BracketType.Open;");
    sb.AppendLine("    }");
    sb.AppendLine();
}

static string Numbers(IEnumerable<int> values)
{
    var lines = new StringBuilder();
    var row = new List<string>();
    foreach (var v in values)
    {
        row.Add(v.ToString(CultureInfo.InvariantCulture));
        if (row.Count != 14) continue;
        lines.AppendLine("        " + string.Join(", ", row) + ",");
        row.Clear();
    }
    if (row.Count > 0) lines.Append("        " + string.Join(", ", row));
    return lines.ToString();
}

static string FindRepoRoot()
{
    var dir = new DirectoryInfo(AppContext.BaseDirectory);
    while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "RtlFix.slnx")))
        dir = dir.Parent;
    return dir?.FullName ?? Directory.GetCurrentDirectory();
}

record Range(int Start, int End, byte Value);

/// <summary>Mirrors the enum emitted into RtlFix.Core so the generated keys line up.</summary>
enum JoiningForm : byte
{
    Isolated = 0,
    Final = 1,
    Initial = 2,
    Medial = 3,
}
